project:
  type: website
  output-dir: docs
  
website:
  title: "Geoscientist Who Codes"
  description: "Aditya Arie Wijaya Personal Website"
  site-url: https://ariewjy.github.io/
  # reader-mode: true
  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: light
  search:
    location: navbar
    type: overlay
  favicon: logo_rounded.png
  twitter-card:
    image: profile.jpg
    creator: "@adtarie"
    card-style: summary_large_image
  # site-url: 
  open-graph: true
  sidebar: 
    style: docked
  navbar:
    background: "#F6F0ED"
    foreground: "#0B2027"
    pinned: false
    right:
      - text: "About" 
        file: about.qmd
      - text: "Blog"
        file: index.qmd
      - icon: github
        href: https://github.com/ariewjy
      - icon: twitter
        href: https://twitter.com/Adtarie
      - icon: linkedin
        href: https://www.linkedin.com/in/adityaariewijaya/
  page-footer: 
    right:
      - text: "Copyright, Aditya Arie Wijaya" 
    left:
      - href: https://www.quarto.org
        text: Built with Quarto
  page-navigation: true
format:
  html:
    theme:
      light: litera
      # dark: darkly
    css: styles.css
    highlight-style: eiffel
    toc: true
    toc-location: right
    fontsize: 1em
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    # mainfont: "system-ui"
    # monofont: "system-ui"
    footnotes-hover: true
    citation: true
    citation-location: margin
    comments:
      utterances:
        repo: ariewjy/quarto-blog
execute: 
  freeze: auto



